name: Publish to TestPyPI

on:
  push:
    tags:
      - "v*.*.*-rc*"

permissions:
  contents: read
  id-token: write   # REQUIRED for Trusted Publisher (OIDC)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build
        run: |
          python -m pip install -U pip build
          python -m build

      - name: Publish (TestPyPI)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
